services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      target: prod
      args:
        WWWUSER: ${WWWUSER}
        WWWGROUP: ${WWWGROUP}
    restart: always
    container_name: l12-app
    working_dir: /var/www
    volumes:
      - .:/var/www:cached
      - .docker/php/supervisord.conf:/etc/supervisord.conf
      - .docker/php/supervisor.conf:/etc/supervisor/conf.d/supervisor.conf
    depends_on:
      - postgres
      - redis
    networks:
      - laravel-12-network

  nginx:
    image: nginx:alpine
    container_name: l12-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-12-network

  postgres:
    image: postgres:16-alpine
    container_name: l12-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - laravel-12-network

  redis:
    image: redis:alpine
    container_name: l12-redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - laravel-12-network

volumes:
  pg_data:
  redis_data:

networks:
  laravel-12-network:
    name: laravel-12-network
    driver: bridge
